### ISSUE TITLE
Fix supported PHP version as in fact PHP 5.2 is not supported since version 1.3

### ISSUE THREAD

**Issue by alquerci** [FriendsOfSymfony1/doctrine1#66]
Actually this library still support the version >=5.2.3 of PHP, this info is on `composer.json`. However, anonymous functions become available on version 5.3.0.

The goal is to make it clear about the minimum PHP version supported.

Note: The same kind of work need to be done for symfony1.

Created from #65

**Comment by thePanz** [comment]
@alquerci can you create a PR for this? I guess composer.json needs to be updated

**Comment by alquerci** [comment]
@thePanz yes for sure I can, added to my todo-list then.

**Comment by thePanz** [comment]
Removal of support for PHP 5.2 is being handled in https://github.com/FriendsOfSymfony1/doctrine1/pull/72
