### ISSUE TITLE
PHP 7.3 Compatibility: "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by arendvw** [FriendsOfSymfony1/doctrine1#76]
When using version 1.3.8 of doctrine 1, using PHP 7.3 will now issue warnings

> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in .../vendor/lexpress/doctrine1/lib/Doctrine/Query/Tokenizer.php on line 96

**Comment by regisnew** [comment]
There are no 1.3.8 version.

**Comment by alquerci** [comment]
Hello @arendvw 

This issue has been fixed on #67 but there is no release yet [tests result][0].

@regisnew One day we will have this version but not yet indeed. It is maybe on a fork.

[0]: https://travis-ci.org/FriendsOfSymfony1/doctrine1/jobs/579584458
