### ISSUE TITLE
Deprecated Warning on "doctrine:build" results in corrupted base files

### ISSUE THREAD

**Issue by JohannesTyra** [FriendsOfSymfony1/doctrine1#95]
The command `php symfony doctrine:build --all-classes --application=backend'`

results into some deprecated warnings 

```
doctrine generating form classes

PHP Deprecated: strtolower(): Passing null to parameter $string) of type string is deprecated in vendor/friendsofsymfony1/doctrine1/lib/Doctrine/Table.php on line 1182
```

***

Afterwords its IN the generated base classes und results in corrupted files.
(because the output is passed there)

**Comment by thirsch** [comment]
Hi @JohannesTyra, thanks for reporting it. Do you have a minimal example for it? While we are using the generator for models and forms as well, we do not have any issues with this. The easy fix would be to add `?? ''` in the method, but I'd like to understand what is going wrong here and add a test as well. Maybe it's just a misconfiguration?

**Comment by JohannesTyra** [comment]
Hi @thirsch, i tried to figure it out.
It´s on 2 places in the generated classes.


`$fieldName` seems to be null in some cases, but i don´t know why.
To the `strtolower($fieldName);` doesn´t work anymore.

I fixed it like that, it will work so far.

`    
public function getColumnName($fieldName)
    {
        // FIX ME: This is being used in places where an array is passed, but it should not be an array
        // For example in places where Doctrine should support composite foreign/primary keys
        $fieldName = is_array($fieldName) ? $fieldName[0]:$fieldName;

        if (isset($this->_columnNames[$fieldName])) {
            return $this->_columnNames[$fieldName];
        }

        if ($fieldName == null){
          return '';
        }

        return strtolower($fieldName);
    }
`

**Comment by akhumphrey** [comment]
We made a similar patch to the `Table::getColumnName()` method on the php81 branch of our fork several months ago too:
```php
public function getColumnName($fieldName)
    {
        // FIX ME: This is being used in places where an array is passed, but it should not be an array
        // For example in places where Doctrine should support composite foreign/primary keys
        $fieldName = is_array($fieldName) ? $fieldName[0] : $fieldName;

        if (isset($this->_columnNames[$fieldName])) {
            return $this->_columnNames[$fieldName];
        }

        if (is_null($fieldName)) {
            return;
        }

        return strtolower($fieldName);
    }
```

No issues discovered so far.
